
[terminal.shell]
program = "/bin/zsh"
args = [ "--login", "-c", "tmux new-session -A -D -s CheverJohn_Always_Love_U" ]

[env]
TERM = "tmux-256color"

[scrolling]
# 滚动历史记录的行数，例如此处设置，会保存最近的 10,000 行历史记录
# 谁知 10,000 行是一个比较常见的选择，既能够提供足够的历史记录，又不会占用过多的内存
history = 10_000
# 每次滚动的时候，滚动的行数，例如此处设置，当鼠标滚轮滚动一次，会滚动3行
multiplier = 3

# 终端响铃
#
# 配置接收到 BEL 控制字符后的
# 每当接收到BEL控制字符时，钟就会响起。
# bell:
  # 动画效果
  #
  # 可以为下面的值，可以设置后自己感受:
  #   - Ease
  #   - EaseOut
  #   - EaseOutSine
  #   - EaseOutQuad
  #   - EaseOutCubic
  #   - EaseOutQuart
  #   - EaseOutQuint
  #   - EaseOutExpo
  #   - EaseOutCirc
  #   - Linear
  # animation: EaseOutExpo

  # 动画闪烁的持续时间（以毫秒为单位）。设置为 0 表示禁用动画效果
  # duration: 0

  # 动画颜色.
  # color: '#ffffff'

  # 响铃后执行的命令， 配置为 None 则不执行任何命令
  #
  # Example:
  #   command:
  #     program: notify-send
  #     args: ["Hello, World!"]
  #
  # command: None
# 这个 bell 配置用于设置当 Alacritty 发出警告声音时的行为
[bell]
# 缓动动画效果为 EaseOutExpo，这个效果会让警告声音的音量逐渐减小
animation = "EaseOutExpo"
# 持续时间为 100 毫秒
duration = 100
# 颜色设置为 green
color = "#ffffff"

##################### selection #####################
[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true 

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/fonts.toml",
  "~/.config/alacritty/keyboard_bindings.toml",
  "~/.config/alacritty/colors.toml",
  "~/.config/alacritty/window.toml",
  "~/.config/alacritty/cursor.toml",
  "~/.config/alacritty/mouse.toml",
  # "~/.config/alacritty/hints.toml",
]

[terminal]
