##################### cursor #####################
# 光标的样式
[cursor]
# 当终端窗口失去焦点时，光标是否变为空心
unfocused_hollow = true
blink_interval = 700
blink_timeout = 3

[cursor.style]
# 光标形状
  #
  # 可以为下面的值:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
shape = "Block"

# 光标闪烁状态
  #
  # 可以为下面的值:
  #   - Never: Prevent the cursor from ever blinking
  #   - Off: Disable blinking by default
  #   - On: Enable blinking by default
  #   - Always: Force the cursor to always blink
blinking = "Always"

# Vi 模式下的光标样式
# 同上面的配置项，如果设置为 None 那么会使用普通模式下的光标配置
[cursor.vi_mode_style]
shape = "Block"
blinking = "Always"



# 毫秒为单位的光标闪烁间隔
# blink_interval: 750

# 如果为true，则当窗口未聚焦时，光标将显示为空心框。 
# unfocused_hollow: true

# Thickness of the cursor relative to the cell width as floating point number
# from `0.0` to `1.0`.
#thickness: 0.15