[[hints]]
enabled = true
command = "open"
hyperlinks = true
post_processing = true
regex = '(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+'

[hints.binding]
key = "U"
mods = "Control|Shift"

[hints.mouse]
enabled = true
mods = "None"