[[keyboard.bindings]]
key = "R"
mods = "Command"
mode = "~Vi|~Search"
chars = "\f"

[[keyboard.bindings]]
key = "R"
mods = "Command"
mode = "~Vi|~Search"
action = "ClearHistory"

# use command + shift + w to close the window
[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "Hide"

[[keyboard.bindings]]
key = "W"
mods = "Command|Shift"
action = "Quit"

# unused Error
[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

# unused Error
[[keyboard.bindings]]
key = "T"
mods = "Command"
action = "CreateNewWindow"

# use alt(option in mac) + left/right to move to the beginning/end of the near word
[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"

# use command + left/right to move to the beginning/end of the line
[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001bOH"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001bOF"
mode = "AppCursor"

# use command + backspace to delete the whole line
[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"

# use command + ' to print "
[[keyboard.bindings]]
key = "'"
mods = "Command"
chars = "\u001d\""
