# 鼠标配置
[mouse]
hide_when_typing = true

[mouse.url]
# 配置单击 URL 时的动作
  #
  # 单击被识别为URL的文本时，将执行所指定的程序。 URL始终作为最后一个参数添加到命令中。 
  # 如果设置为 None，那么禁用此功能
  #
  # Default:
  #   - (macOS) open
  #   - (Linux/BSD) xdg-open
  #   - (Windows) explorer
  # launcher:
  #  program: xdg-open
  #  args: []

  # URL modifiers
  #
  # 配置修饰键，Alacritty 默认单击就打开 URL，如果将此项配置为 Command，那么需要按住 Command 然后单击
modifiers = "Command"

# Mouse bindings
#
# 配置鼠标动作绑定，和键盘绑定类似。详细配置可以参考 Key bindings 一节
# 
# 为了在 Alacritty 中运行的应用程序捕获鼠标时触发鼠标绑定，会自动添加 Shift 修饰符。 
#
# - `mouse`:
#
#   - Middle
#   - Left
#   - Right
#   - Numeric identifier such as `5`
#
# - `action` (see key bindings)
#
# And optionally:
#
# - `mods` (see key bindings)
# mouse_bindings:
# - { mouse: Middle, action: PasteSelection } # 按鼠标中键粘贴选中内容